Extended collection
hiqdev/yii2-hiart pull request #28
Opened 2020-09-21 14:48 UTC by bladeroot

2020-09-21 15:23 UTC, hiqsol requested changes

2020-09-21 15:23 UTC, hiqsol commented on src/Collection.php
> -
насколько я вижу изменений нет, а дифф есть - просто перемещена функция
зачем? верни взад

2020-09-21 15:39 UTC, bladeroot commented on src/Collection.php
> -
И перемещена и изменена область видимости с private на protected
И по PSR порядок const > public > protected > private Потому функция смещена вниз

2020-09-21 15:41 UTC, hiqsol commented on src/Collection.php
> -
тогда ок

2020-11-05 09:27 UTC, hiqsol approved these changes

2020-11-05 13:14 UTC, SilverFire commented
Переименовал `ExtendedCollection` в `MixedCollection`, помержил.

2020-11-05 13:14 UTC, closed without merging